version: '3.1'

services:

  mysql:
    image: mysql:5.7
    container_name: "river-mysql"
#    volumes:
#      - ./data/mysql:/var/lib/mysql
#    ports:
#      - 3310:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: "password"
#      MYSQL_USER: "user"
#      MYSQL_PASSWORD: "password"